const express = require("express")
require("dotenv").config({ path: "./config/.env" })
const PORT = process.env.PORT || 5000
const db = require("./config/db")
db()
const cors = require("cors")
require("colors")
const app = express()
app.use(express.json())
app.use(express.static("public"))
app.use(cors())
app.use("/blogs", require("./routes/blogRoutes"))
app.listen(PORT, console.log(`SERVER RUNNING http://localhost:${PORT}`.bgBlue))